### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by ghost** [Rogerio848484/es-theme-RBHS#14]
I wish I can use the RHBS theme, but download fails whether from GitHub or Batocera...

Can you upload it on google drive or mega ?

This is the last theme I need to acquire all of them

just like the Neon Blast theme here:
https://github.com/Scotty-Retro/Neon-BlastV1/issues/9

Big thanks :smiley:

**Comment by Rogerio848484** [comment]
https://drive.google.com/file/d/1a-yMn3F6BixBuR6J62Qgs9C1PpUBsQ9N/view?usp=share_link


‪Em sex., 24 de mar. de 2023 às 16:03, ‫عَبدُ القَادِر عَبدُ الرَّؤُوف
خَمَّاشْ‬‎ ***@***.***> escreveu:‬

**Comment by ghost** [comment]
@Rogerio848484 
![screenshot-2023 03 26-01h29 56](https://user-images.githubusercontent.com/37517008/227748803-740ee397-8b17-4e34-bba8-6186a9dfd642.png)

Thank you so much !
